import { StyleSheet } from "react-native";
import { colors } from "@/ui/primitives";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  pressed: { opacity: 0.55 },
  toolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 14,
  },
  inboxToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 22,
  },
  profile: {
    height: 44,
    width: 44,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "#3D3B36",
    backgroundColor: "#272723",
    alignItems: "center",
    justifyContent: "center",
  },
  inboxContent: { paddingHorizontal: 18, paddingTop: 3, paddingBottom: 24 },
  conversation: { flexDirection: "row", gap: 14, paddingVertical: 13, alignItems: "center" },
  conversationCopy: { flex: 1, gap: 7 },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  conversationTitle: { color: colors.text, fontSize: 18, fontWeight: "600", flexShrink: 1 },
  timestamp: { color: colors.quiet, fontSize: 13 },
  preview: { color: colors.muted, fontSize: 16, lineHeight: 21 },
  agentPill: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 25,
    backgroundColor: colors.control,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    minHeight: 44,
  },
  agentName: { color: colors.text, fontSize: 17, fontWeight: "600" },
  messages: { paddingHorizontal: 16, paddingBottom: 20, gap: 9 },
  date: {
    color: colors.quiet,
    fontSize: 13,
    textAlign: "center",
    paddingTop: 10,
    paddingBottom: 18,
  },
  assistantBubble: {
    alignSelf: "flex-start",
    maxWidth: "94%",
    backgroundColor: colors.surface,
    borderRadius: 23,
    padding: 15,
    gap: 10,
  },
  userBubble: {
    alignSelf: "flex-end",
    maxWidth: "85%",
    backgroundColor: "#545452",
    borderRadius: 23,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  messageText: { color: colors.text, fontSize: 17, lineHeight: 24, letterSpacing: -0.15 },
  secondaryText: { color: colors.muted, fontSize: 15, lineHeight: 21, flexShrink: 1 },
  choice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 13,
    paddingHorizontal: 13,
    paddingVertical: 13,
    minHeight: 48,
  },
  choiceText: { color: colors.text, fontSize: 16, lineHeight: 22, flexShrink: 1, flexGrow: 1 },
  messageGroup: { gap: 8 },
  working: {
    flexDirection: "row",
    alignSelf: "flex-start",
    alignItems: "center",
    gap: 10,
    padding: 16,
    backgroundColor: colors.surface,
    borderRadius: 22,
  },
  caution: { color: "#E5B77E", fontSize: 13, fontWeight: "500" },
  resultFootnote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minHeight: 32,
    paddingHorizontal: 12,
  },
  footnote: { fontSize: 12, color: colors.quiet },
  composerBar: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 9,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 7,
    backgroundColor: colors.background,
  },
  composerPill: {
    flex: 1,
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 26,
    backgroundColor: colors.control,
    flexDirection: "row",
    alignItems: "flex-end",
    padding: 5,
    paddingLeft: 15,
    gap: 7,
  },
  composerInput: {
    flex: 1,
    color: colors.text,
    fontSize: 17,
    maxHeight: 120,
    paddingTop: 7,
    paddingBottom: 7,
    lineHeight: 22,
  },
  send: {
    width: 34,
    height: 34,
    borderRadius: 18,
    backgroundColor: colors.text,
    alignItems: "center",
    justifyContent: "center",
  },
  sendDisabled: { backgroundColor: "#303030" },
  searchToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 16,
    paddingTop: 20,
  },
  searchPill: {
    flex: 1,
    minHeight: 44,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.control,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 13,
  },
  searchInput: { flex: 1, color: colors.text, fontSize: 17, paddingVertical: 10 },
  filterLabel: { fontSize: 13, color: colors.muted, paddingHorizontal: 24, paddingBottom: 8 },
  empty: { color: colors.muted, fontSize: 15, lineHeight: 22, paddingVertical: 24 },
  infoCard: { backgroundColor: colors.surface, padding: 16, borderRadius: 20, gap: 10 },
  inline: { flexDirection: "row", alignItems: "center", gap: 9 },
  statusDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.green },
  offline: { backgroundColor: colors.quiet },
  confirmRow: { flexDirection: "row", gap: 8 },
  cancelButton: {
    padding: 12,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    minWidth: 80,
    alignItems: "center",
  },
  allowButton: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.background,
    padding: 12,
    borderRadius: 13,
  },
  allowText: { color: colors.text, fontSize: 16 },
});
